### ISSUE TITLE
compile error on FreeBSD/mips

### ISSUE THREAD

**Issue by yamori813** [matsumoto-r/mruby-httprequest#5]
日本語ですみません。

ZRouterというビルドシステムでFreeBSDのシステムとmruby 1.2をmips用にクロスビルドしているのですが、なぜかこの環境でmruby-httprequestを組み込むとビルドエラーになります。

CC    build/zrouter/mrbgems/mruby-simplehttp/gem_init.c -> build/zrouter/mrbgems
/mruby-simplehttp/gem_init.o
      MRBC build/mrbgems/mruby-httprequest/mrblib/httprequest.rb 
CC    build/zrouter/mrbgems/mruby-httprequest/gem_init.c -> build/zrouter/mrbgem
s/mruby-httprequest/gem_init.o
rake aborted!
Command Failed: [cc -O2 -pipe  -fno-strict-aliasing -DMRBGEM_MRUBY_HTTPREQUEST_V
ERSION=0.0.1 -I"/storage/home/hiroki/obj/storage/home/hiroki/zrouter/ports/stora
ge/home/hiroki/zrouter/ports/lang/mruby/mruby-1.2.0/include" -I"/storage/home/hi
roki/obj/storage/home/hiroki/zrouter/ports/storage/home/hiroki/zrouter/ports/lan
g/mruby/mruby-1.2.0/build/mrbgems/mruby-io/include" -I"/storage/home/hiroki/obj/
延々とこれが続きます。

どうも依存がどこかでループしてしまっているようでmruby-httprequestのmrbgem.rakeから

spec.add_dependency('mruby-simplehttp')

を消すとエラーがでなくなります。半年くらい前は問題起きていなかったと思います。

ホストのamd64で同じmgemでビルドすると問題なくビルドが通ります。

現在FreeBSDはamd64はclangなのですが、mipsはgccになっています。

ちょっと調べてみたのですが、理由がまったく分からず、なにかアドバイスあれば教えていただけると助かります。

**Comment by take-cheeze** [comment]
@yamori813
似たような現象にこちらも1.2で遭遇しました。
simplehttpの方で、すでにpolarsslが依存関係に含まれているのが原因だとわかりました。

simplehttpではなくpolarsslの方をコメントアウトした場合の情報をいただけるとありがたいです。

**Comment by yamori813** [comment]
mruby 1.3で試した所、問題起きなくなりました。お騒がせしてすみませんでした。
